version: "3"

services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    environment:
      POSTGRES_USER : myuser
      POSTGRES_PASSWORD : mypassword
      POSTGRES_DB : mydatabase
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "myuser", "-d", "mydatabase","-p 5433"]
      interval : 5s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

networks:
  default:
    name: mlops-network
    external : true



  